//
//  Layout.ts
//
//  Generated by Poll Castillo on 09/03/2023.
//
export const UIContentLayout = `
    <div class="datatable" id="datatable">
        <div class="datatable_header">
            <div class="datatable_title"><h1 id="view-title"></h1></div>
            <div class="datatable_tools" id="datatable-tools">
                <input type="search" class="search_input" placeholder="Buscar" id="search">

                <button class="datatable_button import_user" id="import-entities">Exportar</button>
            </div>
        </div>

        <table class="datatable_content">
        <thead><tr>
            <th><span data-type="title">
            Título <i data-feather="filter"></i>
            </span></th>

            <th><span data-type="content">
            Contenido <i data-feather="filter"></i>
            </span></th>

            <th class="thead_centered" width=220><span data-type="date">
            Fecha <i data-feather="filter"></i>
            </span></th>

            <th class="thead_centered" width=130><span data-type="details">
            Detalles
            </span></th>

        </tr></thead>
        <tbody id="datatable-body" class="datatable_body">

        </tbody>
        </table>

        <div class="datatable_footer">
        <div class="datatable_pagination" id="pagination-container"></div>
        </div>
    </div>`

export const UIRightSidebar = `
<div class="entity_editor" id="entity-editor">
<div class="entity_editor_header">
  <div class="user_info">
    <div class="avatar"><i data-feather="user"></i></div>
    <h1 class="entity_editor_title">Registrar <br><small>Cliente</small></h1>
  </div>

  <button class="btn btn_close_editor" id="close"><i data-feather="x"></i></button>
</div>

<!-- EDITOR BODY -->
<div class="entity_editor_body">
  <div class="material_input">
    <input type="text" id="entity-firstname" autocomplete="none">
    <label for="entity-firstname">Nombre</label>
  </div>

  <div class="material_input">
    <input type="text" id="entity-lastname" autocomplete="none">
    <label for="entity-lastname">Apellido</label>
  </div>

  <div class="material_input">
    <input type="text" id="entity-secondlastname" autocomplete="none">
    <label for="entity-secondlastname">2do Apellido</label>
  </div>

  <div class="material_input">
    <input type="text"
      id="entity-phone"
      maxlength="10" autocomplete="none">
    <label for="entity-phone">Teléfono</label>
  </div>

  <div class="material_input">
    <input type="text" id="entity-username" class="input_filled" placeholder="john.doe@ejemplo.com" readonly>
    <label for="entity-username"><i data-feather="lock" class="input_locked"></i> Nombre de usuario</label>
  </div>

  <div class="material_input_select">
    <label for="entity-state">Estado</label>
    <input type="text" id="entity-state" class="input_select" readonly placeholder="cargando..." autocomplete="none">
    <div id="input-options" class="input_options">
    </div>
  </div>

  <div class="material_input_select">
    <label for="entity-business">Empresa</label>
    <input type="text" id="entity-business" class="input_select" readonly placeholder="cargando..." autocomplete="none">
    <div id="input-options" class="input_options">
    </div>
  </div>

  <div class="material_input_select">
    <label for="entity-citadel">Ciudadela</label>
    <input type="text" id="entity-citadel" class="input_select" readonly placeholder="cargando...">
    <div id="input-options" class="input_options">
    </div>
  </div>

  <div class="material_input_select">
    <label for="entity-customer">Cliente</label>
    <input type="text" id="entity-customer" class="input_select" readonly placeholder="cargando...">
    <div id="input-options" class="input_options">
    </div>
  </div>

  <div class="material_input_select">
    <label for="entity-department">Departamento</label>
    <input type="text" id="entity-department" class="input_select" readonly placeholder="cargando...">
    <div id="input-options" class="input_options">
    </div>
  </div>

  <br><br>
  <div class="material_input">
    <input type="password" id="tempPass" autocomplete="false">
    <label for="tempPass">Contraseña temporal</label>
  </div>

</div>
<!-- END EDITOR BODY -->

<div class="entity_editor_footer">
  <button class="btn btn_primary btn_widder" id="register-entity">Guardar</button>
</div>
</div>
`
