//
//  Layout.ts
//
//  Generated by Poll Castillo on 09/03/2023.
//
export const UIContentLayout = `
    <div class="datatable" id="datatable">
        <div class="datatable_header">
            <div class="datatable_title"><h1 id="view-title"></h1></div>
            <div class="datatable_tools" id="datatable-tools">
                <input type="search" class="search_input" placeholder="Buscar" id="search">

                <button class="datatable_button import_user" id="import-entities">Exportar</button>
            </div>
        </div>

        <table class="datatable_content">
        <thead><tr>
            <th><span data-type="title">
            Título <i class="fa-regular fa-filter"></i>
            </span></th>

            <th><span data-type="content">
            Contenido <i class="fa-regular fa-filter"></i>
            </span></th>

            <th class="thead_centered" width=220><span data-type="date">
            Fecha <i class="fa-regular fa-filter"></i>
            </span></th>

            <th class="thead_centered" width=130><span data-type="details">
            Detalles
            </span></th>

        </tr></thead>
        <tbody id="datatable-body" class="datatable_body">

        </tbody>
        </table>

        <div class="datatable_footer">
        <div class="datatable_pagination" id="pagination-container"></div>
        </div>
    </div>`

export const UIRightSidebar = `
    <div class="entity_editor" id="entity-editor">
    <div class="entity_editor_header">
      <div class="user_info">
        <div class="avatar"><i class="fa-regular fa-user"></i></div>
        <h1 class="entity_editor_title">Detalles de <br><small>la nota</small></h1>
      </div>

      <button class="btn btn_close_editor" id="close"><i class="fa-solid fa-x"></i></button>
    </div>

    <!-- EDITOR BODY -->
    <div class="entity_editor_body">
      <h2 id="note-title">Título</h2>
      <p id="note-content">Lorem ipsum dolor sit amet...</p><br><br>

      <div class="material_input">
        <input type="text" id="note-author" class="input_filled" value="" readonly>
        <label for="note-author"><i class="fa-solid fa-user"></i> Autor</label>
      </div>

      <div class="material_input">
        <input type="text" id="note-creationdate" class="input_filled" value="" readonly>
        <label for="note-creationdate"><i class="fa-solid fa-calendar"></i> Fecha de creación</label>
      </div>

    </div>
    <!-- END EDITOR BODY -->

    <div class="entity_editor_footer">
      <button class="btn btn_primary btn_widder" id="update-changes">Guardar</button>
    </div>
    </div>
    `