//
//  Template.ts
//
//  Generated by Poll Castillo on 09/03/2023.
//
export const UITableSkeletonTemplate = `
<tr>
    <td>Cargando</td>
    <td>Cargando</td>
    <td>Cargando</td>
    <td class="entity_options">
        <button class="button" id="convert-toSuperuser">
            <i data-feather="shield" class="table_icon"></i>
        </button>
    </td>
</tr>`