//
//  interfaces.ts
//
//  Generated by Poll Castillo on 26/02/2023.
//
export interface IEditEntity { editEntity(): void }
export interface IRemoveEntity { removeEntity(): void }
export interface IImportEntity { importEntity(): void }
export interface IToSuperUser { toSuperUser(): void }
export interface IRegisterEntity { registerEntity(): void }
export interface ISearchEntity { searchEntity(): void }
export interface IFilterEntities { filterEntities(): void }