//
//  main.ts
//
//  Generated by Poll Castillo on 15/02/2023.
//
import { connect } from "./connection.js";
import { SignIn } from "./login.js";
import { InterfaceElement } from "./types.js";

new SignIn().checkSignIn()
