//
//  registerWebLogin.ts
//
//  Generated by Poll Castillo on 01/03/2023.

import { _userAgent } from "./endpoints.js"

//
export const registerWebLogin = async (): Promise<void> => {
  const $userAgent: any = _userAgent

  console.log($userAgent)
}