//
//  UserLoggedInfo.ts
//
//  Generated by Poll Castillo on 02/03/2023.
//
import { getUserInfo } from "./endpoints.js";

export const customerName = async (): Promise<string> => {
  const userData: any = await getUserInfo();
  const userDataSlitted: string = userData.attributes.username.split('@')
  const userCustomer: string = userDataSlitted[1].split('.')[0]
  return userCustomer
}

export const currentDate = (): string => {
  let DT = new Date()
  const date = DT.getDate()
  const month = DT.getMonth() + 1
  const year = DT.getFullYear()

  const DATE =
    ('0' + date).slice(-2) + '/' +
    ('0' + month).slice(-2) + '/' +
    year
  return DATE
}
export const currentTime = () => { }