//
//  DashboardMonthlySection.ts
//
//  Generated by Poll Castillo on 23/02/2023.
//

import { InterfaceElement } from "../../types"
import { createChartContext } from "./CreateChartContext.js"

export const renderMonthlyChart = async (): Promise<void> => {
  createChartContext('monthly')
  const chart: InterfaceElement =
    document.getElementById('monthly-chart')

  // @ts-ignore
  new Chart(chart, {
    type: 'bar',
    data: {
      labels: [
        'Sem 1',
        'Sem 2',
        'Sem 3',
        'Sem 4'],
      datasets: [
        {
          label: 'Visitas',
          data: [22, 33, 15, 12],
          borderWidth: 1
        },
        {
          label: 'Marcaciones',
          data: [2, 5, 8, 3],
          borderWidth: 1
        }
      ]
    },
    options: {
      responsive: true,
      plugins: {
        legend: {
          position: 'bottom'
        },
        title: {
          display: true,
          text: 'Registros de este mes'
        }
      },
      scales: {
        y: {
          beginAtZero: true
        }
      }
    }
  })
}